### ISSUE TITLE
Field dim is not necessarily spatial dim

### ISSUE THREAD

**Issue by koehlerson** [Ferrite-FEM/Ferrite.jl#616]
When creating `*VectorValues` it is assumed that the field has the same dimensions as the spatial ones, which is not always the case, e.g. when evaluating gradient fields

**Comment by termi-official** [comment]
Similar for the other dimensions. Reference element dimension is not necessarily spatial dimension and field dimension is also decoupled from vectorization dimension of scalar valued basis functions.

E.g. Nedelec has field dimension D, but only one basis function, wheras vectorized Lagrange has field dimension D with D basis functions per entity.

**Comment by termi-official** [comment]
Relates to #569

**Comment by fredrikekre** [comment]
Fixed by #694 + #651 I think? Comment if not.

**Comment by termi-official** [comment]
Not fully fixed yet. This code still fails
```
using Ferrite
grid = generate_grid(Quadrilateral, (2, 2))
dim = 2
ip = Lagrange{RefQuadrilateral, 1}()
qr_face = QuadratureRule{dim-1, RefQuadrilateral}(2)
facevalues = FaceValues(qr_face, ip^2);
```
because the embedded values was mostly about getting `CellValues` in place. But should be easy to fix.
